export const ROUTES = {
	HOME: '/',
	LOGIN: '/login',
	REGISTER: '/register',
	PRODUCTS: '/products',
	PRODUCT_DETAILS: '/products/[id]',
	COLLECTION_DETAILS: '/collections/[id]',
	ORDERS: '/orders',
	ORDER_DETAILS: '/orders/[id]',
	CUSTOMERS: '/customers',
	CUSTOMER_DETAILS: '/customers/[id]',
	CUSTOMER_GROUP_DETAILS: '/customers/groups/[id]',
	DISCOUNTS: '/discounts',
	GIFT_CARDS: '/gift-cards',
	GIFT_CARD_MANAGE: '/gift-cards/manage',
	GIFT_CARD_DETAILS: '/gift-cards/[id]',
	PRICING: '/pricing',
	MESSAGES: '/messages',
	CALENDAR: '/calendar',
	KANBAN: '/kanban',
	FAQS: '/faqs',

	SETTINGS: {
		DEFAULT: '/settings',
		CURRENCIES: '/settings/currencies',
		PERSONAL_INFORMATION: '/settings/personal-information',
		REGIONS: '/settings/regions',
		RETURN_REASONS: '/settings/return-reasons',
		SALE_CHANNELS: '/settings/sale-channels',
		STORE_DETAILS: '/settings/store-details',
		TAXES: '/settings/taxes',
		TEAM: '/settings/team',
	},
} as const
