export { default as ModalEditProductGeneralInformation } from './modal-edit-product-general-information'
export { default as ProductAttributes } from './product-attributes'
export { default as ProductGeneralInformation } from './product-general-information'
export { default as ProductMedia } from './product-media'
export { default as ProductMetadata } from './product-metadata'
export { default as ProductThumbnail } from './product-thumbnail'
export { default as ProductVariants } from './product-variants'
